# Generated by Django 5.2.17 on 2026-09-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailysales_card_batch_total_dailysales_ending_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysales',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
